/**
 * false.rs
 * 
 * 常にfalse(POSIX規格による異常終了1)を返すプログラム
 */
fn main() {
    std::process::exit(1);
}